[package]
name = "swar"
version = "0.1.1"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["simd", "swar", "bits", "hamming", "parallel"]
documentation = "https://docs.rs/swar/"
repository = "https://github.com/vadixidav/swar"
